version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${CONFIG_PATH}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${ROOT}/downloads:/downloads # downloads folder
      - ${CONFIG_PATH}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${ROOT}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG_PATH}/config/jackett:/config # config files

  # nzbget:
  #   container_name: nzbget
  #   image: linuxserver/nzbget:latest
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #   volumes:
  #     - ${ROOT}/downloads:/downloads # download folder
  #     - ${ROOT}/config/nzbget:/config # config files

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/config/sonarr:/config # config files
      - ${ROOT}/tv:/tv # tv shows folder
      - ${DOWNLOAD_PATH}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/config/radarr:/config # config files
      - ${ROOT}/movies:/movies # movies folder
      - ${DOWNLOAD_PATH}/downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${CONFIG_PATH}/config/plex/db:/config # plex database
      - ${CONFIG_PATH}/config/plex/transcode:/transcode # temp transcoded files
      - ${DOWNLOAD_PATH}:/data # media library

  # bazarr:
  #   container_name: bazarr
  #   image: linuxserver/bazarr
  #   restart: unless-stopped
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID} # default user id, defined in .env
  #     - PGID=${PGID} # default group id, defined in .env
  #     - TZ=${TZ} # timezone, defined in .env
  #     - UMASK_SET=022 #optional
  #   volumes:
  #     - ${ROOT}/config/bazarr:/config # config files
  #     - ${ROOT}/complete/movies:/movies # movies folder
  #     - ${ROOT}/complete/tv:/tv # tv shows folder
  rdtclient:
    container_name: rdtclient
    volumes:
      - '${DOWNLOAD_PATH}/downloads:/data/downloads'
      - '${CONFIG_PATH}/config/rdtclient:/data/db'
    image: rogerfar/rdtclient
    restart: always
    logging:
      driver: json-file
      options:
        max-size: 10m
    network_mode: host
    
