version: "3.4"
services:
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin # required to modify network interfaces
    restart: unless-stopped
    volumes:
      - /dev/net:/dev/net:z # tun device
      - ${CONFIG_PATH}/config/vpn:/vpn # OpenVPN configuration
    security_opt:
      - label:disable
    ports:
      - 8112:8112 # port for deluge web UI to be reachable from local network

  deluge:
    container_name: deluge
    image: linuxserver/deluge:latest
    restart: unless-stopped
    network_mode: service:vpn # run on the vpn network
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - ${DOWNLOAD_PATH}/downloads:/downloads # downloads folder
      - ${CONFIG_PATH}/config/deluge:/config # config files

  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOWNLOAD_PATH}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
      - ${CONFIG_PATH}/config/jackett:/config # config files
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/config/sonarr:/config # config files
      - ${ROOT}/tv:/tv # tv shows folder
      - ${DOWNLOAD_PATH}/downloads:/downloads # download folder

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${CONFIG_PATH}/config/radarr:/config # config files
      - ${ROOT}/movies:/movies # movies folder
      - ${DOWNLOAD_PATH}/downloads:/downloads # download folder

  plex-server:
    container_name: plex-server
    image: mauimauer/spritsail-plex
    restart: unless-stopped
    environment:
      - TZ=${TZ} # timezone, defined in .env
    network_mode: host
    volumes:
      - ${CONFIG_PATH}/config/plex/db:/config # plex database
      - ${CONFIG_PATH}/config/plex/transcode:/transcode # temp transcoded files
      - ${ROOT}:/data # media library
    devices:
      - /dev/dri:/dev/dri
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ=${TZ} # timezone, defined in .env
    # network_mode: host
    ports:
      - 5055:5055
    volumes:
      - ${CONFIG_PATH}/config/overseerr:/app/config
      - ${ROOT}/movies:/movies # movies folder
      - ${DOWNLOAD_PATH}/downloads:/downloads # download folder
      - ${ROOT}/tv:/tv # tv shows folder
      - ${ROOT}/music:/music # tv shows folder
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    network_mode: host
    volumes:
      -  ${CONFIG_PATH}/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      -  ${CONFIG_PATH}/config/nginx/ssl:/ssl/
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      # - /home/ubuntu/ssl:/ssl/
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=${PUID} # default user id, defined in .env
      - PGID=${PGID} # default group id, defined in .env
      - TZ={TZ}
    volumes:
      -  ${CONFIG_PATH}/config/tau:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    
